#!/usr/bin/env python3

import console
from check import checking

#"self" inside the classes allows the function to run, alternatively we can have
#"@staticmethod" above each function (without self in the brackets) and this will work too. 
class SCMapDownloader:	
	def OptionType():
		value = console.userInput()
		choice = SCMapDownloader()
		#Selects which value to take according to the input selected.
		if value == 'c' or value == 'C' or value == "--check":
			choice.interactiveMode('c')
		elif value == 'h' or value == 'H' or value == "--help":
			console.printUsage()
		elif value == 'q' or value == 'Q' or value == "--quit":
			print("Quit")
		else:
			print('Unknown Value')
			console.printUsage()

	def interactiveMode(self, value):
		value = value
		shouldQuit = False

	#This while loop constantly runs and prompts the user for a longitude, latitiude and a zoom level value. 
	#If none are provided, the values used are for Rundle Mall, in the Adelaide CBD. 
	#These longitude and latitude values were generated by Google Maps 
		while shouldQuit != True:
			if value == 'c' or value == 'C' or value == "--check":
				print("Type the latitude to 6 decimal places or press enter for default:")
				latitude = console.userInput()
				if (latitude == ""):
					latitude = -34.922452
					#"-34.922452"
					print("\n >>> Using default (Rundle Mall - Adelaide CBD)", latitude)

				print("\nType the longitude to 6 decimal places or press enter for default:")
				longitude = console.userInput()
				if (longitude == ""):
					longitude = 138.604298
					#"138.604298"
					print("\n >>> Using default (Rundle Mall - Adelaide CBD)", longitude)

				print("\nSpecify the zoom to 2 decimal places between 2.00 and 16.99 or press enter for default:")
				zoom = console.userInput()
				if (zoom == ""):
					zoom = 6.5
					#"6.5"
					print("\n >>> Using default", zoom)

			latitude = float(latitude)
			longitude = float(longitude)
			zoom = float(zoom)

			choice = checking()
			choice.save_console(latitude, longitude, zoom)

			shouldQuit = True
			#Adelaide Convention Center Location: -34.92065185708734, 138.59468391075873
			#Help function within the loop
			# if value == 'h' or value == 'H' or value == "--help":
			# 	console.printUsage()

			# #A seperate if statement within the while, to allow a user to quit
			# if value == 'q' or value == 'Q' or value == "--quit":
			# 	shouldQuit = True
			# 	print("Quit")



# choice = SCMapDownloader()
# choice.OptionType()